openapi: 3.0.3
info:
  title: Tech Challenge - OpenAPI 3.0
  description: |-
  contact:
    email: fiap_ml_pos@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
tags:
  - name: auth
    description: Endpoint para autenticação
  - name: data
    description: Endpoint para leitura dos dados analíticos
  - name: load
    description: Endpoint para carregamento dos dados analíticos
paths:
  /auth:
    post:
      tags:
        - auth
      summary: Autenticação
      description: Autenticação
      operationId: auth
      responses:
        '200':
          description: Autenticação realizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /data/producao:
    post:
      tags:
        - data
      summary: Consulta de dados analíticos
      description: Consulta de dados analíticos
      operationId: getProductionData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDataRequest'      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
      security:
        - api_key: []
  /load:
    post:
      tags:
        - store
      summary: Place an order for a pet
      description: Place a new order in the store
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoadRequest'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    LoadRequest:
      type: object
      properties:
        file_name:
          type: string
          example: '2024-01-01.csv'
    GetDataRequest:
      type: object
      properties:
        group_id:
          type: string
          example: 'ti_'
        year:
          type: string
          example: '2024'
  securitySchemes:
    app_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app/oauth/authorize
          scopes:
            read:data: read data from the database
    api_key:
      type: apiKey
      name: api_key
      in: header