"""add tables

Revision ID: 941d4b4463da
Revises: 
Create Date: 2025-01-14 20:55:39.038662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941d4b4463da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercializacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exportacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('derivado_uva', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('derivado_uva', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classificacao_uva', sa.String(), nullable=False),
    sa.Column('cultivar', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('producao')
    op.drop_table('processamento')
    op.drop_table('importacao')
    op.drop_table('exportacao')
    op.drop_table('comercializacao')
    # ### end Alembic commands ###
