version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - embrapa-network
    restart: unless-stopped

networks:
  embrapa-network:
    driver: bridge 